administration/urls.py
from django.urls import path

from administration.views import (
    AddStreamersView,
    IndexView,
    StreamersView,
    UpdateStreamersFromTwitch,
)

app_name = "administration"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("streamers/", StreamersView.as_view(), name="streamers"),
    path("streamers/add", AddStreamersView.as_view(), name="add-streamers"),
    path(
        "streamers/twitch-update",
        UpdateStreamersFromTwitch.as_view(),
        name="update-streamers",
    ),
    path(
        "streamers/p/list",
        StreamersView.as_view(partial=True),
        name="streamers-partials-list",
    ),
]

pogscience/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path

import debug_toolbar

urlpatterns = [
    path("", include("streamers.urls", namespace="streamers")),
    path("", include("social_django.urls", namespace="social")),
    path("logout/", LogoutView.as_view(next_page="/"), name="logout"),
    path("admin/", include("administration.urls", namespace="administration")),
    path("admin/django/", admin.site.urls),
    path("__debug__/", include(debug_toolbar.urls)),
]

# Serves media in debug mode
if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

streamers/urls.py
from django.urls import path

from streamers.views.eventsub import EventSubIngestView
from streamers.views.public import CalendarView, HomeView
from streamers.views.api import (
    LiveAndUpcomingAPIView,
    ScheduledStreamsAPIView,
    StreamersResourcesAPIView,
)
from streamers.views.raid import RaidAPIView

app_name = "streamers"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("calendrier", CalendarView.as_view(), name="calendar"),
    path("api/live-and-upcoming", LiveAndUpcomingAPIView.as_view(), name="api-live-upcoming"),
    path("api/scheduled", ScheduledStreamsAPIView.as_view(), name="api-scheduled"),
    path("api/streamers-resources", StreamersResourcesAPIView.as_view(), name="api-streamers-resources"),
    path("api/raid/<str:twitch_login>", RaidAPIView.as_view(), name="api-raid"),
    path("twitch/eventsub/ingest", EventSubIngestView.as_view(), name="eventsub-ingest"),
]

website/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
]

streamers/models.py
import binascii
import colorsys
import os
from datetime import timedelta
from io import BytesIO
from urllib.error import HTTPError
from uuid import UUID

import requests
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.models import AbstractUser
from django.core import files
from django.core.management.utils import get_random_secret_key
from django.db import models
from django.db.models import Q
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from pogscience.storage import OverwriteStorage
from pogscience.twitch import get_twitch_client
from streamers.utils import extract_main_colours, grouper


class User(AbstractUser):
    pass


def image_upload_to(folder):
    """
    Generates a function returning the filename to use for a streamer profile
    picture, or background image, or other. The image will be named against the
    streamer, in the given folder.

    :param folder: The folder where to store the image.
    :return: A function for Django FileField's upload_to.
    """

    def _inner(instance, filename: str):
        """
        Used by Django, returns the filename to use for the streamers' profile
        pictures.
        """
        _, ext = os.path.splitext(filename)
        return f"twitch/{folder}/{instance.twitch_login}{ext}"

    return _inner


def profile_image_upload_to(*args, **kwargs):
    return image_upload_to("profile")(*args, **kwargs)


def background_image_upload_to(*args, **kwargs):
    return image_upload_to("background")(*args, **kwargs)


def live_preview_image_upload_to(*args, **kwargs):
    return image_upload_to("live-preview")(*args, **kwargs)


class Streamer(models.Model):
    """
    A streamer, member of PogScience.
    """

    class Meta:
        verbose_name = _("streamer")
        verbose_name_plural = _("streamers")
        ordering = ["name", "twitch_login"]

    EVENTSUB_SUBSCRIPTIONS = ["stream.online", "stream.offline", "channel.update"]

    user = models.OneToOneField(
        User,
        on_delete=models.SET_NULL,
        verbose_name=_("compte interne du streamer"),
        null=True,
        blank=True,
        default=None,
    )

    name = models.CharField(
        verbose_name=_("nom du streamer"),
        max_length=128,
        help_text=_("Le nom d'affichage du/de la streamer⋅euse"),
    )
    twitch_login = models.CharField(
        verbose_name=_("nom d'utilisateur Twitch"),
        max_length=64,
        help_text=_("Utilisé pour récupérer les informations automatiquement"),
    )
    twitch_id = models.PositiveBigIntegerField(
        verbose_name=_("identifiant numérique Twitch"),
        help_text=_("Utilisé pour récupérer les informations automatiquement"),
    )
    description = models.CharField(
        verbose_name=_("courte description"),
        max_length=512,
        help_text=_("Une courte description affichée par exemple sur la page d'accueil"),
        blank=True,
    )
    long_description = models.TextField(
        verbose_name=_("longue description"),
        help_text=_("Description potentiellement très longue affichée sur la page du streamer ou de la streameuse"),
        blank=True,
    )
    profile_image = models.ImageField(
        verbose_name=_("image de profil"),
        storage=OverwriteStorage(),
        upload_to=profile_image_upload_to,
        null=True,
        blank=True,
    )
    background_image = models.ImageField(
        verbose_name=_("image de fond"),
        storage=OverwriteStorage(),
        upload_to=background_image_upload_to,
        null=True,
        blank=True,
    )
    _colours = models.CharField(
        verbose_name=_("couleurs"),
        help_text=_(
            "Liste de trois couleurs principales à utiliser pour habiller ce/cette streamer/euse. Les valeurs "
            "sont stockées sous la forme d'une liste de nombres flottants, dont chaque triplet forme une "
            "couleur RGB."
        ),
        # max 7 chars per rgb value, three rgb tuples, and 8 comma separators
        max_length=71,  # 7*3*3 + 8
        blank=True,
        null=True,
        db_column="colours",
    )

    live = models.BooleanField(
        verbose_name=_("en live ?"),
        help_text=_("Est-iel en live actuellement ? Mis à jour automatiquement"),
        default=False,
    )
    live_title = models.CharField(
        verbose_name=_("titre du live"),
        max_length=140,
        blank=True,
        null=True,
        default=None,
        help_text=_("Le titre du live en cours, récupéré automatiquement depuis Twitch"),
    )
    live_game_name = models.CharField(
        verbose_name=_("catégorie du stream"),
        max_length=140,
        blank=True,
        null=True,
        default=None,
        help_text=_("La catégorie du live en cours, récupéré automatiquement depuis Twitch"),
    )
    live_started_at = models.DateTimeField(
        verbose_name=_("début du stream"),
        blank=True,
        null=True,
        default=None,
        help_text=_("L'heure de début du live en cours"),
    )
    live_preview = models.ImageField(
        verbose_name=_("aperçu du live"),
        storage=OverwriteStorage(),
        upload_to=live_preview_image_upload_to,
        null=True,
        blank=True,
    )
    live_spectators = models.PositiveIntegerField(
        verbose_name=_("spectateurs"),
        blank=True,
        null=True,
        default=None,
    )

    def __str__(self):
        return self.name

    @property
    def twitch_url(self):
        return f"https://twitch.tv/{self.twitch_login}"

    @property
    def live_duration(self):
        return timezone.now() - self.live_started_at if self.live_started_at else None

    @property
    def colours(self):
        return list(map(tuple, grouper(map(float, self._colours.split(",")), 3)))

    @colours.setter
    def colours(self, value):
        flat = [val for colour in value for val in colour]
        self._colours = ",".join(map(str, flat))

    @colours.deleter
    def colours(self):
        self._colours = None

    @property
    def colours_hex(self):
        return list(
            map(lambda colour: "#" + binascii.hexlify(bytearray(int(c) for c in colour)).decode("ascii"), self.colours)
        )

    @property
    def colours_hsl(self):
        def rgb_to_hsl(colour):
            h, l, s = colorsys.rgb_to_hls(*map(lambda c: c / 255.0, colour))
            return h * 360, s * 100, l * 100

        return list(map(rgb_to_hsl, self.colours))

    @property
    def colours_hsl_css(self):
        hsl = self.colours_hsl
        return list(map(lambda hsl: f"hsl({hsl[0]}, {hsl[1]}%, {hsl[2]}%)", hsl))

    @staticmethod
    def _download_and_store_image(url, field):
        if not url:
            return

        res_image = requests.get(url)
        if not res_image.ok:
            return

        image = BytesIO()
        image.write(res_image.content)
        filename = f"image{os.path.splitext(url)[1]}"
        field.save(filename, files.File(image), save=False)

    def update_from_twitch_data(self, twitch_data):
        """
        Updates this instance using the data returned by Twitch. Does not save
        the instance.

        :param twitch_data: The Twitch data: https://dev.twitch.tv/docs/api/reference#get-users
        """
        self.name = twitch_data["display_name"]

        self.twitch_id = twitch_data["id"]
        self.twitch_login = twitch_data["login"]

        self.description = twitch_data["description"]

        self._download_and_store_image(twitch_data.get("profile_image_url"), self.profile_image)
        self._download_and_store_image(twitch_data.get("offline_image_url"), self.background_image)
        self.update_colours()

    def update_stream_from_twitch_data(self, twitch_data):
        """
        Updates the current stream using the data returned by Twitch. Does not
        save the instance.
        :param twitch_data: The Twitch data: https://dev.twitch.tv/docs/api/reference#get-streams
        """
        self.live_title = twitch_data["title"]
        self.live_game_name = twitch_data["game_name"]
        self.live_spectators = twitch_data["viewer_count"]

        thumbnail = (
            twitch_data["thumbnail_url"]
            .replace("{width}", str(settings.POG_PREVIEWS["WIDTH"]))
            .replace("{height}", str(settings.POG_PREVIEWS["HEIGHT"]))
        )

        self._download_and_store_image(thumbnail, self.live_preview)

    def update_stream(self):
        """
        Updates this streamer's current stream (if the streamer is live and
        Twitch returns a stream for it).
        """
        client = get_twitch_client()
        streams = client.get_streams(user_ids=[self.twitch_id])
        try:
            self.update_stream_from_twitch_data(streams[0])
        except IndexError:
            # The streamer is not live: Twitch returned nothing about its stream.
            pass

    def start_stream(self):
        """
        Starts the current stream, and store the start time of it for later use (see `end_stream`).
        Does not save the Streamer instance.
        """
        self.live = True
        self.live_started_at = timezone.now()

    def end_stream(self):
        """
        Ends the current stream, and mark any corresponding scheduled stream as “done”, so
        they wont show up on the homepage if the stream finished in advance.
        Does not save the Streamer instance.
        """
        self.live = False

        if self.live_started_at:
            scheduled_streams_count = ScheduledStream.objects.filter(
                streamer=self, start__lte=timezone.now(), end__gte=self.live_started_at
            ).update(done=True, start=self.live_started_at, end=timezone.now())

            # If there was no scheduled stream, we create one matching the stream, to have

administration/views.py
import re
from http import HTTPStatus

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db import transaction
from django.forms import model_to_dict
from django.http import Http404, HttpResponse, JsonResponse
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import FormView, ListView, RedirectView

from pogscience.twitch import get_twitch_client

from administration.forms import AddStreamersForm
from streamers.models import Streamer


class IndexView(LoginRequiredMixin, RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        if self.request.user.has_perm("streamers.view_streamer"):
            return reverse_lazy("administration:streamers")

        raise Http404()


class StreamersView(PermissionRequiredMixin, LoginRequiredMixin, ListView):
    partial = False
    permission_required = ["streamers.view_streamer"]
    model = Streamer
    context_object_name = "streamers"

    extra_context = {"add_streamers_form": AddStreamersForm()}

    def get_template_names(self):
        return "streamers/list.partial.html" if self.partial else "streamers/list.html"


class AddStreamersView(PermissionRequiredMixin, LoginRequiredMixin, FormView):
    permission_required = ["streamers.add_streamer"]
    template_name = "streamers/add.html"
    form_class = AddStreamersForm
    success_url = reverse_lazy("administration:streamers")

    def form_valid(self, form):
        # Splits the names at whitespaces (including new lines) and filter out
        # empty strings left for multiple separators.
        streamer_names = [name for name in re.split(r",|\s", form.cleaned_data["streamers_names"].strip()) if name]

        streamers_twitch = get_twitch_client().get_users(streamer_names)

        with transaction.atomic():
            for streamer in streamers_twitch:
                try:
                    streamer_model: Streamer = Streamer.objects.get(twitch_login=streamer["login"])
                except Streamer.DoesNotExist:
                    streamer_model: Streamer = Streamer()

                streamer_model.update_from_twitch_data(streamer)
                streamer_model.save()

                streamer_model.subscribe_to_eventsub()

            Streamer.full_twitch_sync()

        return HttpResponse(status=HTTPStatus.CREATED)


class UpdateStreamersFromTwitch(PermissionRequiredMixin, LoginRequiredMixin, View):
    permission_required = ["streamers.change_streamer"]

    def post(self, request):
        streamers = Streamer.objects.all()
        ids = [streamer.twitch_id for streamer in streamers]
        # We use string keys because Twitch returns string ids
        streamers = {str(streamer.twitch_id): streamer for streamer in streamers}

        streamers_twitch = get_twitch_client().get_users(ids=ids)

        for streamer in streamers_twitch:
            streamer_model = streamers[streamer["id"]]
            streamer_model.update_from_twitch_data(streamer)
            streamer_model.save()

        return HttpResponse(status=HTTPStatus.NO_CONTENT)

streamers/views.py
from django.db.models import OuterRef, Subquery
from django.utils import timezone
from django.views.generic import TemplateView

from streamers.models import ScheduledStream, Streamer


class HomeView(TemplateView):
    template_name = "home.html"
    extra_context = {
        "streamers": Streamer.objects.all(),
        "live_streamers": Streamer.objects.filter(live=True),
    }

    def get_context_data(self):
        now = timezone.now()

        context = super(HomeView, self).get_context_data()
        context["streamers"] = Streamer.objects.all()

        # We want scheduled stream that were not started yet (i.e.
        # the corresponding streamer is not live) and where the *end* time
        # is in the future (so streams starting late are still displayed).
        context["scheduled"] = ScheduledStream.objects.filter(streamer__live=False, end__gte=now).prefetch_related(
            "streamer"
        ).order_by('start')[:4]

        # We try to associate live streamers with the corresponding planned stream, so we can display
        # the end time.
        context["live_streamers"] = Streamer.objects.filter(live=True).annotate(
            live_end=Subquery(
                ScheduledStream.objects.filter(streamer=OuterRef("pk"), start__lte=now, end__gte=now)
                .order_by("start")
                .values("end")[:1]
            )
        )

        context["now"] = now

        return context

streamers/views/public.py
import random

from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.decorators.vary import vary_on_cookie
from django.views.generic import TemplateView

from streamers.models import Streamer


# vary_on_cookie ensures the cache is never shared between users
@method_decorator([cache_page(3600), vary_on_cookie], name="dispatch")
class HomeView(TemplateView):
    template_name = "home.html"

    def get_context_data(self):
        context = super(HomeView, self).get_context_data()

        streamers = list(Streamer.objects.all())
        random.shuffle(streamers)
        context["streamers"] = streamers

        return context


class CalendarView(TemplateView):
    template_name = "calendar.html"

administration/templates/streamers/add.html
{% extends "admin_base.html" %}
{% load bulma_tags %}

{% block admin_title %}Nouveaux streamers{% endblock %}
{% block admin_subtitle %}Pog grandit ?{% endblock %}

{% block admin_content %}
    <p class="block">
        Ajoutez des streamers en entrant un pseudo Twitch par ligne dans le
        champ ci-dessous. Nous récupèrerons les informations de base sur chacun⋅e
        automatiquement.
    </p>

    <form action="" method="POST">
        {% csrf_token %}
        {{ form|bulma_inline }}

        <div class="control">
          <input type="submit" class="button is-primary" value="Ajouter les streamers" />
        </div>
    </form>
{% endblock %}

administration/templates/streamers/list.html
{% extends "admin_base.html" %}
{% load bulma_tags i18n %}

{% block admin_title %}Streamers
    <span class="tag is-primary is-light is-rounded">{{ streamers|length }}</span>{% endblock %}

{% block admin_title_right %}
    {% if perms.streamers.change_streamer %}
        <div class="level-item">
            <button class="button is-primary is-light js-update-streamers">
                <span class="icon"><span class="fas fa-sync-alt"></span></span>
                <span>Actualiser depuis Twitch</span>
            </button>
        </div>
    {% endif %}
    {% if perms.streamers.add_streamer %}
        <div class="level-item">
            <button class="button is-primary is-light js-add-streamers">
                <span class="icon"><span class="fas fa-plus"></span></span>
                <span>Ajouter des streamers</span>
            </button>
        </div>
    {% endif %}
    {% if user.is_staff and perms.streamers.change_streamer or perms.streamers.delete_streamer %}
        <div class="level-item">
            <a href="{% url "admin:streamers_streamer_changelist" %}" class="button is-primary is-light" title="{% trans "Plus d'options d'administration" %}">
                <span class="icon"><span class="fas fa-ellipsis-h"></span></span>
            </a>
        </div>
    {% endif %}
{% endblock %}

{% block admin_content %}
    <div class="columns is-multiline" id="js-streamers-list">
        {% include "streamers/list.partial.html" %}
    </div>

    {% if perms.streamers.add_streamer %}
        <div class="modal" id="js-add-streamers-modale">
            <div class="modal-background"></div>
            <div class="modal-card">
                <form action="" method="POST" id="js-add-streamers-form">
                    <header class="modal-card-head">
                        <p class="modal-card-title">{% trans "Ajouter des streamers à PogScience" %}</p>
                    </header>
                    <section class="modal-card-body">
                        <p class="block">
                            {% blocktrans %}
                                Ajoutez des streamers en entrant un pseudo Twitch par ligne dans le
                                champ ci-dessous. Nous récupèrerons les informations de base sur chacun⋅e
                                automatiquement.
                            {% endblocktrans %}
                        </p>
                        {% csrf_token %}
                        {{ add_streamers_form|bulma_inline }}
                    </section>
                    <footer class="modal-card-foot">
                        <button class="button is-primary" type="submit">{% trans "Ajouter les streamers" %}</button>
                        <button class="button is-text modal-close-handler">{% trans "Annuler" %}</button>
                    </footer>
                </form>
            </div>
            <button class="modal-close is-large" aria-label="{% trans "Fermer" %}"></button>
        </div>
    {% endif %}
{% endblock %}

administration/templates/streamers/list.partial.html
{% load i18n %}

{% for streamer in streamers %}
    <div class="column is-half">
        <div class="card admin-streamer">
            <div class="card-content">
                <div class="media">
                    <div class="media-left">
                        <figure class="image is-64x64">
                            <img src="{{ streamer.profile_image.url }}" alt="{{ streamer.name }}">
                        </figure>
                    </div>
                    <div class="media-content">
                        <p class="title is-4">
                            {{ streamer.name }}
                            {% if streamer.live %}<span class="tag is-danger">LIVE</span>{% endif %}
                        </p>
                        <p class="subtitle is-6"><a href="https://twitch.tv/{{ streamer.twitch_login }}"
                                                    target="_blank">@{{ streamer.twitch_login }}</a></p>
                    </div>
                </div>

                <div class="content">
                    {{ streamer.description }}
                </div>
            </div>
            <footer class="card-footer">
                <a href="#" class="card-footer-item">{% trans "Voir" %}</a>

                {% if perms.streamers.change_streamer or streamer.user == user %}
                    <a href="#" class="card-footer-item">{% trans "Modifier" %}</a>
                {% endif %}
                {% if user.is_staff and perms.streamers.delete_streamer %}
                    <a href="{% url "admin:streamers_streamer_delete" streamer.id %}" class="card-footer-item">{% trans "Supprimer" %}</a>
                {% endif %}
            </footer>
        </div>
    </div>
{% empty %}
    <div class="column is-half is-offset-one-quarter has-text-centered mt-5">
        <p class="title is-4 block">Il n'y a personne d'enregistré…</p>
        {% if perms.streamers.add_streamer %}
            <p class="block">
                Cliquez ci-dessous pour ajouter tout le monde ! Vous pourrez
                ajouter plusieurs personnes d'un coup, et nous récupèrerons
                automatiquement les données de base depuis Twitch.
            </p>
            <button class="button is-primary js-add-streamers block">
                <span class="icon"><span class="fas fa-plus"></span></span>
                <span>Ajouter des streamers <span class="is-hidden-mobile">à PogScience</span></span>
            </button>
        {% else %}
            <p class="block">{% trans "Un⋅e administrateur⋅trice peut ajouter du monde dans PogScience." %}</p>
        {% endif %}
    </div>
{% endfor %}