administration/urls.py
from django.urls import path

from administration.views import (
    AddStreamersView,
    IndexView,
    StreamersView,
    UpdateStreamersFromTwitch,
)

app_name = "administration"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("streamers/", StreamersView.as_view(), name="streamers"),
    path("streamers/add", AddStreamersView.as_view(), name="add-streamers"),
    path(
        "streamers/twitch-update",
        UpdateStreamersFromTwitch.as_view(),
        name="update-streamers",
    ),
    path(
        "streamers/p/list",
        StreamersView.as_view(partial=True),
        name="streamers-partials-list",
    ),
]

pogscience/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path

import debug_toolbar

urlpatterns = [
    path("", include("streamers.urls", namespace="streamers")),
    path("", include("social_django.urls", namespace="social")),
    path("logout/", LogoutView.as_view(next_page="/"), name="logout"),
    path("admin/", include("administration.urls", namespace="administration")),
    path("admin/django/", admin.site.urls),
    path("__debug__/", include(debug_toolbar.urls)),
]

# Serves media in debug mode
if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
]

templates/base.html
{% load bulma_tags %}
{% load static %}
{% load render_bundle from webpack_loader %}

<!DOCTYPE html>
<html lang="fr">

<head itemscope>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta itemprop="csrfmiddlewaretoken" content="{{ csrf_token }}"/>

    {% render_bundle 'main' 'css' is_preload=True %}
    {% render_bundle 'main' 'js' is_preload=True %}

    <title>{% block title %}PogScience{% endblock %}</title>

    {% render_bundle 'main' 'css' %}
    {% font_awesome %}
</head>

<body>
{% block body %}
    {% block content %}{% endblock %}

    <footer class="footer">
        <div class="content has-text-centered">
            <p>
                {% if request.user.is_anonymous %}
                    <a href="{% url "social:begin" "twitch" %}">
                        Se connecter avec Twitch
                    </a>
                {% else %}
                    {{ request.user.username }} &centerdot;
                    <a href="{% url "administration:index" %}">
                        Administration
                    </a> &centerdot;
                    <a href="{% url "logout" %}">
                        Déconnexion
                    </a>
                {% endif %}
            </p>
        </div>
    </footer>
{% endblock %}

{% render_bundle 'main' 'js' %}
{% block js %}{% endblock %}
</body>
</html>